name: ayiqsurucu_operator
description: Ayiq Sürücü Operator Panel
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.1.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  socket_io_client: ^2.0.3+1
  intl: 0.20.2
  flutter_rating_bar: ^4.0.1
  image_picker: ^1.0.4
  file_picker: ^6.1.1
  url_launcher: ^6.2.1
 
  syncfusion_flutter_datagrid: ^30.1.41
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
