class AppLocalizations {
  static const Map<String, Map<String, String>> _localizedValues = {
    'en': {
      // Login Screen
      'welcome': 'Welcome!',
      'enterCredentials': 'Enter your username and password to continue',
      'username': 'Username',
      'enterUsername': 'Enter your username',
      'password': 'Password',
      'enterPassword': 'Enter your password',
      'login': 'Login',
      'usernameRequired': 'Username is required',
      'usernameMinLength': 'Username must be at least 3 characters',
      'passwordRequired': 'Password is required',
      'passwordMinLength': 'Password must be at least 6 characters',
      'loginWithCredentials': 'Login with username and password',
      'error': 'Error',
      'ok': 'OK',
      'loginFailed': 'Login failed',

      // Registration Screen
      'driverRegistration': 'Driver Registration',
      'fillInfoToWork': 'Fill in your information to work as a driver',
      'licenseNumber': 'Driver License Number',
      'licenseHint': 'AZE123456789',
      'licenseRequired': 'Driver license number is required',
      'privacyPolicyAccepted': 'I have read and accept the privacy policy',
      'readPrivacyPolicy': 'Read Privacy Policy',
      'privacyPolicy': 'Privacy Policy',
      'privacyPolicyRequired': 'You must accept the privacy policy',
      'completeRegistration': 'Complete Registration',
      'registrationInfo':
          'After registration, your information will be verified and you can start working after approval',
      'registrationFailed': 'Registration failed',

      // Dashboard
      'dashboard': 'Dashboard',
      'online': 'Online',
      'offline': 'Offline',
      'goOnline': 'Go Online',
      'goOffline': 'Go Offline',
      'activeOrders': 'Active Orders',
      'orderHistory': 'Order History',
      'earnings': 'Earnings',
      'welcomeDriver': 'Hello, {name}! 👋',
      'onlineReady': 'Online and ready',
      'readyToStart': 'You can start working when ready',
      'todayStats': 'Today\'s Statistics',
      'orders': 'Orders',
      'balance': 'Balance',
      'today': 'Today',
      'home': 'Home',
      'addressCopied': 'Address information copied',
      'textShareError': 'Text sharing error',
      'driver': 'Driver',
      // Orders
      'newOrder': 'New Order',
      'orderDetails': 'Order Details',
      'pickupLocation': 'Pickup Location',
      'destination': 'Destination',
      'customer': 'Customer',
      'fare': 'Fare',
      'accept': 'Accept',
      'decline': 'Decline',
      'startTrip': 'Start Trip',
      'completeTrip': 'Complete Trip',
      'cancelTrip': 'Cancel Trip',
      'pickup': 'Pickup',
      'delivery': 'Delivery',
      'details': 'Details',
      'noAddress': 'No address',
      'paymentMethod': 'Payment Method',
      'notes': 'Notes',
      'estimatedTime': 'Estimated Time',
      'estimatedDistance': 'Estimated Distance',
      'eta': 'ETA',
      'minutes': 'minutes',
      'km': 'km',
      'cash': 'Cash',
      'card': 'Card',
      'pending': 'Pending',
      'accepted': 'Accepted',
      'driverAssigned': 'Driver Assigned',
      'driverArrived': 'Driver Arrived',
      'inProgress': 'In Progress',
      'completed': 'Completed',
      'cancelled': 'Cancelled',
      'newOrderAssigned': 'New Order Assigned!',
      'assignedByOperator': 'Assigned by operator',
      'orderNumber': 'Order #',
      'contact': 'Contact',
      'reject': 'Reject',

      // Profile Screen
      'profile': 'Profile',
      'personalInfo': 'Personal Information',
      'fullName': 'Full Name',
      'phone': 'Phone',
      'email': 'Email',
      'registrationDate': 'Registration Date',
      'noData': 'No data available',
      'dailyEarnings': 'Daily Earnings',
      'weeklyEarnings': 'Weekly Earnings',
      'editProfile': 'Edit Profile',
      'language': 'Language',
      'logout': 'Logout',
      'settings': 'Settings',
      'selectLanguage': 'Select Language',
      'english': 'English',
      'russian': 'Русский',
      'uzbek': 'O\'zbek',
      'azerbaijani': 'Azərbaycan',

      // Status
      'approved': 'Approved',
      'rejected': 'Rejected',
      'suspended': 'Suspended',
      'unknown': 'Unknown',

      // Image Picker
      'selectProfileImage': 'Select Profile Image',
      'camera': 'Camera',
      'gallery': 'Gallery',

      // Error Messages
      'errorOccurred': 'An error occurred',
      'tryAgain': 'Try Again',

      // Common
      'loading': 'Loading...',
      'save': 'Save',
      'cancel': 'Cancel',
      'close': 'Close',
      'yes': 'Yes',
      'no': 'No',
      'confirm': 'Confirm',
      'success': 'Success',
      'failed': 'Failed',
    },
    'ru': {
      // Login Screen
      'welcome': 'Добро пожаловать!',
      'enterCredentials': 'Введите имя пользователя и пароль для продолжения',
      'username': 'Имя пользователя',
      'enterUsername': 'Введите ваше имя пользователя',
      'password': 'Пароль',
      'enterPassword': 'Введите ваш пароль',
      'login': 'Войти',
      'usernameRequired': 'Имя пользователя обязательно',
      'usernameMinLength':
          'Имя пользователя должно содержать минимум 3 символа',
      'passwordRequired': 'Пароль обязателен',
      'passwordMinLength': 'Пароль должен содержать минимум 6 символов',
      'loginWithCredentials': 'Войти с именем пользователя и паролем',
      'error': 'Ошибка',
      'ok': 'ОК',
      'loginFailed': 'Вход не удался',

      // Registration Screen
      'driverRegistration': 'Регистрация водителя',
      'fillInfoToWork': 'Заполните вашу информацию для работы водителем',
      'licenseNumber': 'Номер водительского удостоверения',
      'licenseHint': 'AZE123456789',
      'licenseRequired': 'Номер водительского удостоверения обязателен',
      'privacyPolicyAccepted':
          'Я прочитал и принимаю политику конфиденциальности',
      'readPrivacyPolicy': 'Прочитать политику конфиденциальности',
      'privacyPolicy': 'Политика конфиденциальности',
      'privacyPolicyRequired': 'Вы должны принять политику конфиденциальности',
      'completeRegistration': 'Завершить регистрацию',
      'registrationInfo':
          'После регистрации ваша информация будет проверена, и вы сможете начать работать после одобрения',
      'registrationFailed': 'Регистрация не удалась',

      // Dashboard
      'dashboard': 'Панель управления',
      'online': 'Онлайн',
      'offline': 'Офлайн',
      'goOnline': 'Выйти онлайн',
      'goOffline': 'Выйти офлайн',
      'activeOrders': 'Активные заказы',
      'orderHistory': 'История заказов',
      'earnings': 'Заработок',
      'welcomeDriver': 'Привет, {name}! 👋',
      'onlineReady': 'Онлайн и готов',
      'readyToStart': 'Вы можете начать работать, когда будете готовы',
      'todayStats': 'Статистика за сегодня',
      'orders': 'Заказы',
      'balance': 'Баланс',
      'today': 'Сегодня',
      'home': 'Главная',
      'addressCopied': 'Информация об адресе скопирована',
      'textShareError': 'Ошибка при обмене текстом',
      'driver': 'Водитель',
      'profile': 'Профиль',

      // Orders
      'newOrder': 'Новый заказ',
      'orderDetails': 'Детали заказа',
      'pickupLocation': 'Место посадки',
      'destination': 'Назначение',
      'customer': 'Клиент',
      'fare': 'Тариф',
      'accept': 'Принять',
      'decline': 'Отклонить',
      'startTrip': 'Начать поездку',
      'completeTrip': 'Завершить поездку',
      'cancelTrip': 'Отменить поездку',
      'pickup': 'Посадка',
      'delivery': 'Доставка',
      'details': 'Подробности',
      'noAddress': 'Нет адреса',
      'paymentMethod': 'Способ оплаты',
      'notes': 'Примечания',
      'estimatedTime': 'Примерное время',
      'estimatedDistance': 'Примерное расстояние',
      'eta': 'Время прибытия',
      'minutes': 'минут',
      'km': 'км',
      'cash': 'Наличные',
      'card': 'Карта',
      'pending': 'Ожидает',
      'accepted': 'Принят',
      'driverAssigned': 'Водитель назначен',
      'driverArrived': 'Водитель прибыл',
      'inProgress': 'В процессе',
      'completed': 'Завершен',
      'cancelled': 'Отменен',
      'newOrderAssigned': 'Новый заказ назначен!',
      'assignedByOperator': 'Назначен оператором',
      'orderNumber': 'Заказ №',
      'contact': 'Контакт',
      'reject': 'Отклонить',

      // Profile Screen
      'personalInfo': 'Личная информация',
      'fullName': 'Полное имя',
      'phone': 'Телефон',
      'email': 'Электронная почта',
      'registrationDate': 'Дата регистрации',
      'noData': 'Данные недоступны',
      'dailyEarnings': 'Дневной доход',
      'weeklyEarnings': 'Недельный доход',
      'editProfile': 'Редактировать профиль',
      'language': 'Язык',
      'logout': 'Выйти',
      'settings': 'Настройки',
      'selectLanguage': 'Выберите язык',
      'english': 'English',
      'russian': 'Русский',
      'uzbek': 'O\'zbek',
      'azerbaijani': 'Azərbaycan',

      // Status
      'approved': 'Одобрен',
      'rejected': 'Отклонен',
      'suspended': 'Приостановлен',
      'unknown': 'Неизвестно',

      // Image Picker
      'selectProfileImage': 'Выберите фото профиля',
      'camera': 'Камера',
      'gallery': 'Галерея',

      // Error Messages
      'errorOccurred': 'Произошла ошибка',
      'tryAgain': 'Попробовать снова',

      // Common
      'loading': 'Загрузка...',
      'save': 'Сохранить',
      'cancel': 'Отмена',
      'close': 'Закрыть',
      'yes': 'Да',
      'no': 'Нет',
      'confirm': 'Подтвердить',
      'success': 'Успешно',
      'failed': 'Не удалось',
    },
    'uz': {
      // Login Screen
      'welcome': 'Xush kelibsiz!',
      'enterCredentials':
          'Davom etish uchun foydalanuvchi nomi va parolingizni kiriting',
      'username': 'Foydalanuvchi nomi',
      'enterUsername': 'Foydalanuvchi nomingizni kiriting',
      'password': 'Parol',
      'enterPassword': 'Parolingizni kiriting',
      'login': 'Kirish',
      'usernameRequired': 'Foydalanuvchi nomi talab qilinadi',
      'usernameMinLength':
          'Foydalanuvchi nomi kamida 3 ta belgi bo\'lishi kerak',
      'passwordRequired': 'Parol talab qilinadi',
      'passwordMinLength': 'Parol kamida 6 ta belgi bo\'lishi kerak',
      'loginWithCredentials': 'Foydalanuvchi nomi va parol bilan kirish',
      'error': 'Xatolik',
      'ok': 'OK',
      'loginFailed': 'Kirish muvaffaqiyatsiz',

      // Registration Screen
      'driverRegistration': 'Haydovchi ro\'yxatdan o\'tkazish',
      'fillInfoToWork':
          'Haydovchi sifatida ishlash uchun ma\'lumotlaringizni to\'ldiring',
      'licenseNumber': 'Haydovchilik guvohnomasi raqami',
      'licenseHint': 'AZE123456789',
      'licenseRequired': 'Haydovchilik guvohnomasi raqami talab qilinadi',
      'privacyPolicyAccepted': 'Maxfiylik siyosatini o\'qidim va qabul qilaman',
      'readPrivacyPolicy': 'Maxfiylik siyosatini o\'qish',
      'privacyPolicy': 'Maxfiylik siyosati',
      'privacyPolicyRequired': 'Maxfiylik siyosatini qabul qilishingiz kerak',
      'completeRegistration': 'Ro\'yxatdan o\'tkazishni yakunlash',
      'registrationInfo':
          'Ro\'yxatdan o\'tkazgandan so\'ng ma\'lumotlaringiz tekshiriladi va tasdiqlangandan keyin ishlay boshlashingiz mumkin',
      'registrationFailed': 'Ro\'yxatdan o\'tkazish muvaffaqiyatsiz',

      // Dashboard
      'dashboard': 'Boshqaruv paneli',
      'online': 'Onlayn',
      'offline': 'Oflayn',
      'goOnline': 'Onlayn bo\'lish',
      'goOffline': 'Oflayn bo\'lish',
      'activeOrders': 'Faol buyurtmalar',
      'orderHistory': 'Buyurtmalar tarixi',
      'earnings': 'Daromad',
      'welcomeDriver': 'Salom, {name}! 👋',
      'onlineReady': 'Onlayn va tayyor',
      'readyToStart': 'Tayyor bo\'lganda ishlay boshlashingiz mumkin',
      'todayStats': 'Bugungi statistika',
      'orders': 'Buyurtmalar',
      'balance': 'Balans',
      'today': 'Bugun',
      'home': 'Bosh sahifa',
      'addressCopied': 'Manzil ma\'lumotlari nusxalandi',
      'textShareError': 'Matn almashish xatoligi',
      'driver': 'Haydovchi',
      'profile': 'Profil',

      // Orders
      'newOrder': 'Yangi buyurtma',
      'orderDetails': 'Buyurtma tafsilotlari',
      'pickupLocation': 'Olish joyi',
      'destination': 'Manzil',
      'customer': 'Mijoz',
      'fare': 'Tarif',
      'accept': 'Qabul qilish',
      'decline': 'Rad etish',
      'startTrip': 'Sayohatni boshlash',
      'completeTrip': 'Sayohatni yakunlash',
      'cancelTrip': 'Sayohatni bekor qilish',
      'pickup': 'Olish',
      'delivery': 'Yetkazish',
      'details': 'Tafsilotlar',
      'noAddress': 'Manzil yo\'q',
      'paymentMethod': 'To\'lov usuli',
      'notes': 'Izohlar',
      'estimatedTime': 'Taxminiy vaqt',
      'estimatedDistance': 'Taxminiy masofa',
      'eta': 'Kelish vaqti',
      'minutes': 'daqiqa',
      'km': 'km',
      'cash': 'Naqd',
      'card': 'Karta',
      'pending': 'Kutilmoqda',
      'accepted': 'Qabul qilindi',
      'driverAssigned': 'Haydovchi tayinlandi',
      'driverArrived': 'Haydovchi keldi',
      'inProgress': 'Jarayonda',
      'completed': 'Yakunlandi',
      'cancelled': 'Bekor qilindi',
      'newOrderAssigned': 'Yangi buyurtma tayinlandi!',
      'assignedByOperator': 'Operator tomonidan tayinlandi',
      'orderNumber': 'Buyurtma №',
      'contact': 'Aloqa',
      'reject': 'Rad etish',

      // Profile Screen
      'personalInfo': 'Shaxsiy ma\'lumotlar',
      'fullName': 'To\'liq ism',
      'phone': 'Telefon',
      'email': 'Elektron pochta',
      'registrationDate': 'Ro\'yxatdan o\'tish sanasi',
      'noData': 'Ma\'lumot mavjud emas',
      'dailyEarnings': 'Kunlik daromad',
      'weeklyEarnings': 'Haftalik daromad',
      'editProfile': 'Profilni tahrirlash',
      'language': 'Til',
      'logout': 'Chiqish',
      'settings': 'Sozlamalar',
      'selectLanguage': 'Tilni tanlang',
      'english': 'English',
      'russian': 'Русский',
      'uzbek': 'O\'zbek',
      'azerbaijani': 'Azərbaycan',

      // Status
      'approved': 'Tasdiqlangan',
      'rejected': 'Rad etilgan',
      'suspended': 'To\'xtatilgan',
      'unknown': 'Noma\'lum',

      // Image Picker
      'selectProfileImage': 'Profil rasmini tanlang',
      'camera': 'Kamera',
      'gallery': 'Galereya',

      // Error Messages
      'errorOccurred': 'Xatolik yuz berdi',
      'tryAgain': 'Qayta urinish',

      // Common
      'loading': 'Yuklanmoqda...',
      'save': 'Saqlash',
      'cancel': 'Bekor qilish',
      'close': 'Yopish',
      'yes': 'Ha',
      'no': 'Yo\'q',
      'confirm': 'Tasdiqlash',
      'success': 'Muvaffaqiyat',
      'failed': 'Muvaffaqiyatsiz',
    },
  };

  static String getString(String key, String language) {
    return _localizedValues[language]?[key] ??
        _localizedValues['en']![key] ??
        key;
  }

  static List<String> getSupportedLanguages() {
    return _localizedValues.keys.toList();
  }

  static String getLanguageName(String languageCode) {
    switch (languageCode) {
      case 'en':
        return 'English';
      case 'ru':
        return 'Русский';
      case 'uz':
        return 'O\'zbek';
      default:
        return languageCode;
    }
  }
}
